### ISSUE TITLE
End Mage has infinite range regardless of offhand item and does not consume mana

### ISSUE THREAD

**Issue by joemama098463** [QuantumXenon/origins-plus-plus#121]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft 1.19.2
- Mod Loader Version (newest on 9minecraft)
- Origins Version (newest on 9minecraft)
- Origins++ Version (newest on 9minecraft)
- Pehkui Version (newest on 9minecraft)

**Origin**
End Mage

**Power**
secret ability that allows mage to have infinite range with enderpearl in offhand (always active regardless of offhand item)

**Notes**
I'm using the 9Minecraft versions because for whatever reason when I use the curseforge version the mod just simply does not do anything

**Comment by joemama098463** [comment]
*note: "newest" refers to newest available versions from December 24th of this year

**Comment by jg2002-j** [comment]
hey, sorry to re-open this, but I was unable to use this either I had an enderpearl in offhand. i cant teleport to any blocks in sight, and I cant pull mobs to me either (everything still works in the normal range limit)

Minecraft 1.19.2 | Forge 43.2.14
origins-forge-1.19.2-1.7.1.1-all.jar
origins-plus-plus-2.1.1-forge.jar
origins-classes-forge-1.2.0.jar
ExtraKeybindsForge-1.1-1.19.x.jar


also not sure if I should make an additional post for this but there appear to be delays between using the abilities wasn't sure if this was intentional?
