### ISSUE TITLE
XL Packets as a Dependency

### ISSUE THREAD

**Issue by Hammerkirby123** [QuantumXenon/origins-plus-plus#188]
**Loader**
Forge
**Versions**
- Minecraft Version -1.19.2
- Origins Version -1.7.1.0
- Origins++ Version -2.0.1
- Pehkui Version -3.7.3

**Notes**
When starting up minecraft, XL packets causes a bunch or mods to load incorrectly
for example
Naturalist, Paragon, Deeper and Darker, GeckoLib, The graveyard, Ars Nouveau, and even forge itself
these are just based on the mods i currently have
When loaded without XL packets, i get an exit code 1
is there some other mod that can increase packets that can be required?

**Comment by Sad-yst** [comment]
from what i noticed, some dependencies aren't compatible
try removing mod by mod or sending crash log/latest log 
xl packets don't need anything else to work at least not from version 1.18.1 +
make sure you have caelus api installed and if you want to try you can try downloading extra thick packets or double packet size and see if it works, though the best advice would be going through the log and removing conflicting mods

**Comment by QuantumXenon** [comment]
The reason that XL Packets is a dependency is because of `Invalid Player Data` error caused by the login packet for a player to be too large. I was getting a lot of reports for this, so I made it a dependency to avoid them. 

You could try without it (after modifying the `mods.toml` dependencies), but I highly doubt that it would work especially with other mods. If another mod that has similar functionality to XL Packets is compatible with other mods (such as the ones you listed) and still fixes the `Invalid Player Data` error, please let me know and I can switch the dependency to it.

**Comment by QuantumXenon** [comment]
In the next version, I `mods.toml` will no longer require XL Packets or Connectivity, but Origins++ will log a warning if neither are installed. I also plan to mark them as mandatory on CurseForge so that users will have them downloaded automatically, but you can remove them if you would like.

**Comment by QuantumXenon** [comment]
I am closing this as with the current version of Origins (Forge), XL Packets is needed for it to not crash when loading into worlds. Maybe in the future if this is resolved, then I will remove it as a dependency
