### ISSUE TITLE
Server-side spam logs, do these affect the normal operation of the mod?

### ISSUE THREAD

**Issue by Qian-F** [QuantumXenon/origins-plus-plus#210]
https://mclo.gs/0t9APdy

fabric 1.18.2

**Comment by QuantumXenon** [comment]
This is not supposed to happen, and I suspect is because you are using an older version of Minecraft. I believe the fields that it is complaining about are no longer mandatory, so the newer versions do not have issues with it, but the powers will likely not work as expected. 

I will look into adding the fields back (as long as they do not break newer versions) to maintain compatibility with 1.18.2 as that is something I would like to keep.
