### ISSUE TITLE
[Flea] Mount

### ISSUE THREAD

**Issue by FiftiethTerror5** [QuantumXenon/origins-plus-plus#221]
*Please check the pinned issue "Known Forge Issues" before posting a new report*

**Loader**
 Fabric

**Versions**
- 1.19.2
- Origins++ Version

**Origin**
Flea

**Power**
cant eat when hitting a mob/player and have to relog
**Notes**
were playing on a server and the flea origin struggles with bugs like crashing when riding players and not getting food when hitting mobs and players

**Comment by QuantumXenon** [comment]
The power to eat actually is a random chance between strength, haste, resistance, regeneration, speed, and saturation - so you could have been getting another effect instead of saturation. I have reduced the cooldown and increased the weight of saturation, so it should become easier to feed. 

As for the mounting, I think this is an issue with Origins itself as I have seen many reports of issues to do with it even with other origins
