### ISSUE TITLE
[Bug?] clear command spam

### ISSUE THREAD

**Issue by itzTerra** [QuantumXenon/origins-plus-plus#229]
**Loader**
Fabric

**Versions**
- Minecraft Version
  - 1.20
- Mod Loader Version
- Origins Version
- Origins++ Version
  - 2.1
- Pehkui Version

**Origin**
Deathsworn

**Power**
loop

--------

**Notes**
In `data/origins-plus-plus/functions/deathsworn/loop.mcfunction`:
```mcfunction
execute as @e[tag=Deathsworn_Minion] at @s run particle minecraft:witch ~ ~1 ~ 0.25 0.25 0.25 0.01 1

execute as @a[nbt={Inventory:[{tag:{lnc:2}}]}] at @s run effect give @s minecraft:instant_health
clear @a minecraft:magma_cream{lnc:2} 1
``` 

The clear command runs on every player, every tick, even if nobody selected Deathsworn as their origin, and even if Deathsworn is disabled in the config.

> I verified this using a mixin injection log in the ClearCommand's execute function and deleting the `clear...` line after. (I had an unsafe ClearCommand mixin in the first place and this mod broke my mod. However, I fixed it on my end.)

I think this isn't right, **but** I have very little understanding of this data-driven modding and this might be just a limitation of it?

**Comment by QuantumXenon** [comment]
This is because Origins++ is a datapack packaged as a mod, so it only affects the game through Origins. This issue is as a result of this limitation, so while it is not the ideal thing to be doing, as far as I know, it must be done for the origin to work as intended with the setup being the way it is.

Thanks for the investigation and report though!
