### ISSUE TITLE
stargazer cant attack outside starlight mode

### ISSUE THREAD

**Issue by macaronibagel** [QuantumXenon/origins-plus-plus#235]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader** forge

**Versions**
- Minecraft Version 1.19.2
- Mod Loader Version forge - 43.2.0 
- Origins Version 1.19.2-1.7.1.0
- Origins++ Version 2.1.1-forge
- Pehkui Version 3.7.6+1.19.2-forge

**Origin**
What origin is causing the problem?
stargazer 
**Power**
What power is causing the problem?
during the day i cant attack at all even when outside of starlight mode, i also have permanent weakness even at night 
**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
Stargazers have weakness during the day, so do no damage if only using their fist. If you were not able to damage, even with a weapon, this should be fixed with the most recent version of Origins (Forge). 

I tested this in a world with just Origins++ (and latest versions of dependencies) and I did not experience any issues - they might have been fixed in an update since you had the issue.
