### ISSUE TITLE
Ryu origin clears username color

### ISSUE THREAD

**Issue by ABSOLUTEMAX123** [QuantumXenon/origins-plus-plus#367]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Fabric/Quilt
**Versions**
- 1.20.1
- 0.25.0
- 1.10.0
- 2.2
- 3.8.0

**Origin**
Ryu

**Power**
Unkown

**Notes**
when changing colors of username (in this case clover, a color and pronoun datapack), it immedeately resets

**Comment by QuantumXenon** [comment]
This seems to be caused by the way Clover works - after testing, it seems that the username colour/pronouns are done by adding the player to a team, however Origins++ uses this same feature for certain origins (such as the Ryu) to, for example, make mobs not attack them.

This means that specific origins (either in Origins++, or others that use teams) will break Clover, and there isn't really anything that can be done about it. I apologise for any inconvenience.
