### ISSUE TITLE
Javafml:43? 

### ISSUE THREAD

**Issue by MaxmillianP** [QuantumXenon/origins-plus-plus#95]
![unknown](https://user-images.githubusercontent.com/98341535/198401613-fcd091dc-4c39-4317-bd0c-424dab1b0e66.png)
I am making a modpack for a friend group server and I ran into that (the image that's above below or wherever github put it), I have no clue what that means and how to fix that

**Comment by QuantumXenon** [comment]
javafml:43 means Forge for 1.19.2. I've set the mod to only work on 1.19.2+ on Forge because of a serious bug where keybinds did not work properly

**Comment by unseenyounggamer** [comment]
why is the pack marked for 1.18.2 then??? if it isnt able to be used on that version

**Comment by Youhadabadday** [comment]
I agree. Why can't you just simply fix the bug? What part of the code is stopping you from getting a patch out for that issue?

**Comment by QuantumXenon** [comment]
@Youhadabadday @unseenyounggamer 
The bug is with Origins (Forge) itself. Because I have one file for Forge and Fabric, the 1.18.1/1.18.2 are for the Fabric version only. From the next version onwards, I plan to split the files again on CurseForge so that I can correctly mark versions and dependencies for the separate mod loaders. Sorry if this was unclear
